# Load all packages
library(tidyverse)
library(tidymodels)
library("pec")
library(Metrics)
library(ggpubr)
library(rlang)
library(forecast)
library(plyr)
library(dplyr)
library(tidyr)
library(lubridate)
library(kcde)
library(SpecsVerification)
library(xtable)
library(epiR)
library(pROC)
library(spdep)
library(data.table)
library(scoringRules)
library(scoringutils)
library(plyr)
library(dplyr)
library(ggplot2)
library(geosphere)
library(gridExtra)
library(mgcv)
library("ggh4x")
# library(rphylopic)
library(cowplot)
library(ggnewscale)
library(mgcv)
library(MuMIn)
library(texreg)
library(WaveletComp)
library(plyr)
library(RColorBrewer)
library(tidyverse)
library(viridis)
library(xgbstack)
library(densitystackr)
library(covidcast)
library(dlnm)
# library(SpatialEpi)
library(grid)
library(tsModel)
library(INLA)
library(RColorBrewer)
library(quantmod)
library(maps)
library(caret)
library(leafem)
library(htmlwidgets)
library(PropCIs)
library(mapview)
library(splines)
library(rstan)
library(readxl)
library(ubigeo)
library(remotes)
library(mapsPERU)
library(ISOweek)
library(ggpp)
library(gghighlight)
library(terra)

# Base directory
peru.province.base.dir <- file.path(getwd(), "data")

# DIRECTORIES
peru.data.in.dir <- file.path(peru.province.base.dir, "climate")
peru.spi6.in.dir <- file.path(peru.province.base.dir, "spi6")
peru.province.data.dir <- file.path(peru.province.base.dir, "shapefiles")
peru.province.python.dir <- file.path(peru.province.base.dir, "python")
peru.province.python.data.dir <- file.path(peru.province.base.dir, "python/data")
peru.province.python.out.dir <- file.path(peru.province.base.dir, "python/output")
peru.province.spei.dir <- file.path(peru.province.base.dir, "data/spei")
peru.province.out.dir <- file.path(peru.province.base.dir, "output")
peru.province.inla.data.in.dir <- file.path(peru.province.base.dir, "INLA/Input")
peru.province.inla.data.out.dir <- file.path(peru.province.base.dir, "INLA/Output")
peru.province.wavelet.out.dir <- file.path(peru.province.base.dir, "wavelet/Output")
peru.province.wavelet.annual_power.out.dir <- file.path(peru.province.base.dir, "wavelet/Output/annual_power")
peru.province.wavelet.multi_power.out.dir <- file.path(peru.province.base.dir, "wavelet/Output/multi_power")
peru.province.xgb.out.dir <- file.path(peru.province.base.dir, "xgb/Output")
peru.province.ensemble.out.dir <- file.path(peru.province.base.dir, "ensemble/Output")

peru.case_data.in.dir <- file.path(peru.province.base.dir, "cases") # 2010_2021_cases_full_data.csv
peru.province <- peru.province.base.dir # icen.txt

# Create output directories
dir.create(peru.province.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.python.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.python.data.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.inla.data.in.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.inla.data.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.wavelet.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.wavelet.annual_power.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.wavelet.multi_power.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.xgb.out.dir, recursive = TRUE, showWarnings = FALSE)
dir.create(peru.province.ensemble.out.dir, recursive = TRUE, showWarnings = FALSE)

# Boundaries
piura_tumbes_lambayeque <- c("Piura", "Tumbes", "Lambayeque")
peru_district_boundaries2 <- st_read(file.path(peru.province.data.dir, "per_admbnda_adm2_ign_20200714.shp"))
piura_tumbes_lambayeque_boundaries <- subset(peru_district_boundaries2, peru_district_boundaries2$ADM1_ES %in%
  piura_tumbes_lambayeque)
tmp2 <- st_as_sf(peru_district_boundaries2)
tmp2 <- as_Spatial(tmp2)

# Set up province areas
province_areas_dt <- data.table(PROVINCE = tmp2$ADM2_ES, REGION_AREA_KM2 = area(tmp2) / 1e+06)
ptl_province_areas_dt <- subset(province_areas_dt, PROVINCE %in% piura_tumbes_lambayeque_boundaries$ADM2_ES)
