#Load all packages 
require(tidyverse)
require(tidymodels)
require("ranger")
require("pec")
require(Metrics)
require(randomForestSRC)
# require(drf)
require(quantregForest)
require(xgboost)
require(sarimaTD)
require(ggpubr)
require(rlang)
require(forecast)
require(plyr)
require(dplyr)
require(tidyr)
require(lubridate)
require(kcde)
require("astsa")
require(sarima)
require(SpecsVerification)
require(xtable)
require(epiR)
require(pROC)
require(SpiecEasi)
require(spdep)
require(data.table)
require(scoringRules)
require(scoringutils)
require(plyr)
require(dplyr)
require(ggplot2)
require(geosphere)
require(gridExtra)
require(mgcv)
require("ggh4x")
require(rphylopic)
require("ggtree")
require(cowplot)
require(ggnewscale)
require(mgcv)
require(MuMIn)
require(texreg)
require(WaveletComp)
require(plyr)
require(RColorBrewer)
require(tidyverse)
require(viridis)
require(xgbstack)
require(densitystackr)
require(covidcast)
require(quantmod)
require(dlnm)
require(SpatialEpi)
require(grid)
require(tsModel)
require(INLA)
require(RColorBrewer)
require(quantmod)
require(maps)
require(caret)
require(leafem)
require(htmlwidgets)
require(PropCIs)
require(mapview)
require(splines)
require(rstan)
require(readxl)
require(ubigeo)
require(remotes)
require(mapsPERU) # For centroids of provinces
require(ISOweek)
require(quantgen)#
require(ggpp)
require(gghighlight)

# Base directory
peru.province.base.dir <- file.path(getwd(), "data")

# DIRECTORIES
peru.province.data.dir <- file.path(peru.province.base.dir, "data")
peru.province.python.dir <- file.path(peru.province.base.dir, "python")
peru.province.python.data.dir <- file.path(peru.province.base.dir, "python/data")
peru.province.python.out.dir <- file.path(peru.province.base.dir, "python/output")
peru.province.spei.dir <- file.path(peru.province.base.dir, "data/spei")
peru.province.out.dir <- file.path(peru.province.base.dir, "output")
peru.province.inla.data.in.dir <- file.path(peru.province.base.dir, "INLA/Input")
peru.province.inla.data.out.dir <- file.path(peru.province.base.dir, "INLA/Output")
peru.province.wavelet.out.dir <- file.path(peru.province.base.dir, "wavelet/Output")
peru.province.wavelet.annual_power.out.dir <- file.path(peru.province.base.dir, "wavelet/Output/annual_power")
peru.province.wavelet.multi_power.out.dir <- file.path(peru.province.base.dir, "wavelet/Output/multi_power")
peru.province.xgb.out.dir <- file.path(peru.province.base.dir, "xgb/Output")
peru.province.ensemble.out.dir <- file.path(peru.province.base.dir, "ensemble/Output")

# Create output directories
dir.create(peru.province.out.dir, recursive = TRUE)
dir.create(peru.province.python.dir, recursive = TRUE)
dir.create(peru.province.inla.data.out.dir, recursive = TRUE)
dir.create(peru.province.wavelet.out.dir, recursive = TRUE)
dir.create(peru.province.wavelet.annual_power.out.dir, recursive = TRUE)
dir.create(peru.province.wavelet.multi_power.out.dir, recursive = TRUE)
dir.create(peru.province.xgb.out.dir, recursive = TRUE)
dir.create(peru.province.ensemble.out.dir, recursive = TRUE)

# Boundaries
piura_tumbes_lambayeque <- c("Piura","Tumbes","Lambayeque")
peru_district_boundaries2 <- st_read(file.path(peru.province.data.dir, "per_admbnda_adm2_ign_20200714.shp"))
piura_tumbes_lambayeque_boundaries <- subset(peru_district_boundaries2,
                                             peru_district_boundaries2$ADM1_ES %in% piura_tumbes_lambayeque)
tmp2 <- st_as_sf(peru_district_boundaries2)
tmp2 <- as_Spatial(tmp2)

# Set up province areas
province_areas_dt <- data.table(PROVINCE = tmp2$ADM2_ES, REGION_AREA_KM2 = area(tmp2)/ 1000000)
ptl_province_areas_dt <- subset(province_areas_dt, PROVINCE %in% piura_tumbes_lambayeque_boundaries$ADM2_ES)

