import os
from glob import glob

dirstem = config['dirstem']
filestem = config['filestem']

rule all:
    input:
        ['.'.join(file.split('.')[:-1]) for file in glob(f'{dirstem}/{filestem}_*.RDS.trigger')]

rule pbf:
    input:
        trigger = ancient(f'{dirstem}/{filestem}_{{date}}.RDS.trigger'),
        script = ancient('workflows/forecasting/pbf/workflow/scripts/pbf.R'),
    output:
        outfile = f"{dirstem}/{filestem}_{{date}}.RDS",
    params:
        outdir = dirstem,
    shell:
        """
        mkdir -p {params.outdir}
        Rscript {input.script} \
            --date {wildcards.date} \
            --output {output.outfile}
        """
